parameters:
  name: 'BuildLinux'
  vmImage: 'ubuntu-18.04'
  linkType: 'static'

jobs:
  - job: ${{ parameters.name }}
    timeoutInMinutes: 0
    pool:
      vmImage: ${{ parameters.vmImage }}
    steps:
      - script: sudo /bin/sh -c 'wget https://github.com/earthly/earthly/releases/latest/download/earthly-linux-amd64 -O /usr/local/bin/earthly && chmod +x /usr/local/bin/earthly && /usr/local/bin/earthly bootstrap --with-autocomplete'
        displayName: Install Earthly
      - script: |
          sudo apt-get install qemu binfmt-support qemu-user-static
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker stop earthly-buildkitd || true
        displayName: Install QEMU
      - script: earthly +build-multiarch --LINK_TYPE=${{ parameters.linkType }}
        displayName: Build
      - bash: |
          set -ex
          [ "`./bin/${{ parameters.linkType }}/linux/amd64/neko -version`" == "$(NEKO_VERSION)" ]
        displayName: Check version
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: ${{ parameters.name }}Binaries-$
          targetPath: bin/${{ parameters.linkType }}/linux/amd64/neko-$(NEKO_VERSION)-linux64.tar.gz
      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: ${{ parameters.name }}Binaries-arm64
          targetPath: bin/${{ parameters.linkType }}/linux/arm64/neko-$(NEKO_VERSION)-linux64.tar.gz
